name: Java CI and Deploy to Cloudsmith

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: read
  id-token: write  # Necessary for GH Identity Provider to write the JWT token which Cloudsmith needs to read

env:
  CLOUDSMITH_ORG: cloudsmith-test
  #cloudsmith-test 
  #globex-innovations
  CLOUDSMITH_REPO: acme1
  SERVICE: ralph_oidc
  #ci_acme_service
  #oidc_ciara 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Show CPU count
        run: |
          echo "nproc reports: $(nproc)"
          echo "lscpu summary:"
          lscpu | grep '^CPU(s):'

      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      # 3) Clear local Maven cache (optional)
      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository/*

      # 4a) Get ephemeral token
      - name: Auth to Cloudsmith with OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only: 'true'
          pip-install: false

      # 4b) Configure Maven settings (Pull & Push to Cloudsmith)
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>cloudsmith</id>
                <username>${{env.SERVICE}}</username>
                <password>${CLOUDSMITH_API_KEY}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>cloudsmith</id>
                <name>Cloudsmith – mirror of Central</name>
                <url>https://maven.cloudsmith.io/${CLOUDSMITH_ORG}/${CLOUDSMITH_REPO}/</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF
          
      # Debug: Show Maven settings to verify correctness (remove before production)
      - name: Debug Generated Maven Settings
        run: cat ~/.m2/settings.xml

      # 5) Build with Maven
      - name: Build with Maven
        #run: mvn clean package --settings ~/.m2/settings.xml -U
        #run: mvn -T 1C -Dmaven.artifact.threads=12 clean verify --settings ~/.m2/settings.xml -U
        #run:  mvn -B -s ~/.m2/settings.xml -Daether.dependencyCollector.impl=bf -Dmaven.artifact.threads=4 dependency:resolve
        run: mvn -T 1C clean verify --settings ~/.m2/settings.xml -U -Daether.dependencyCollector.impl=bf -Dmaven.artifact.threads=4

        
      # 6) Deploy to Cloudsmith
      - name: Deploy to Cloudsmith
        run: mvn deploy --settings ~/.m2/settings.xml
        
